# application-docker.yml (Docker 실행 시 사용될 설정)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/welibrary?serverTimezone=Asia/Seoul
    username: root
    password: root
